url_1 = 'https://bonigarcia.dev/selenium-webdriver-java/data-types.html'
first_name = 'Иван'
last_name = 'Петров'
address = 'Ленина, 55-3'
email = 'test@skypro.com'
phone = '+7985899998787'
city = 'Москва'
country = 'Россия'
job = 'QA'
company = 'SkyPro'

url_2 = 'https://bonigarcia.dev/selenium-webdriver-java/slow-calculator.html'

url_3 = 'https://www.saucedemo.com/'
login = 'standard_user'
user_password = 'secret_sauce'
f_name = 'Полина'
l_name = 'Шаимова'
postal_code = '454000'
